### ISSUE TITLE
你好，偶然发现你的博客主题很漂亮，请问开源吗？

### ISSUE THREAD

**Issue by jerry011235** [geekplux/geekplux.github.io#1]
你好，偶然发现你的博客主题很漂亮，请问开源吗？
能否把主题文件代码共享出来呢？
谢谢！

**Comment by geekplux** [comment]
https://github.com/hexojs/hexo-theme-landscape

**Comment by jerry011235** [comment]
你好，我也用hexo，我的意思是能否把你修改后的博客主题开源，而不是这个hexo的默认主题。
比如如何让文章模块居中，而分类、tags在下面等等。
也希望你能理解小白修改代码不容易，如果可以的话，能否把你本地的D:\hexo\themes中主题文件夹（landscape？）打包发到我的邮件：jerry011235@gmail.com
快过年了，祝你新的一年开开心心，万事如意～

**Comment by geekplux** [comment]
嗯，我也是小白，不过我还是建议你认真看一下landscape的README。里面有如何配置你所说的「让文章模块居中，而分类、tags在下面等等」。

**Comment by jerry011235** [comment]
多谢，原来如此。
